// <auto-generated />
using System;
using BlogPost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPost.Migrations.Application
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241123151416_AddConstraintsNew")]
    partial class AddConstraintsNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogPost.Models.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PostId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Post");
                });

            modelBuilder.Entity("BlogPost.Models.Topic", b =>
                {
                    b.Property<Guid>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TopicId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            TopicId = new Guid("255e4b03-dbf0-4d1b-b6d4-4f894c785ea8"),
                            Name = "Tech"
                        },
                        new
                        {
                            TopicId = new Guid("30077f43-2d78-470d-844b-03d8dfe07c84"),
                            Name = "Science"
                        },
                        new
                        {
                            TopicId = new Guid("e60e65d0-9f58-4996-9d25-bd24be81354a"),
                            Name = "Health"
                        },
                        new
                        {
                            TopicId = new Guid("a4d23bb2-8be8-4ef4-891b-91fbb88b9356"),
                            Name = "Religion"
                        },
                        new
                        {
                            TopicId = new Guid("e532cc4b-44be-4ff3-a948-b5488dc2b15d"),
                            Name = "Life"
                        },
                        new
                        {
                            TopicId = new Guid("6f7fd266-af92-4281-bf37-c2db7166e596"),
                            Name = "Natural"
                        });
                });

            modelBuilder.Entity("BlogPost.Models.TopicsPosts", b =>
                {
                    b.Property<Guid>("TopicsPostsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TopicsPostsId");

                    b.HasIndex("TopicId");

                    b.HasIndex("PostId", "TopicId")
                        .IsUnique();

                    b.ToTable("TopicsPosts");
                });

            modelBuilder.Entity("BlogPost.Models.TopicsPosts", b =>
                {
                    b.HasOne("BlogPost.Models.Post", "Post")
                        .WithMany("TopicsPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPost.Models.Topic", "Topic")
                        .WithMany("TopicsPosts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BlogPost.Models.Post", b =>
                {
                    b.Navigation("TopicsPosts");
                });

            modelBuilder.Entity("BlogPost.Models.Topic", b =>
                {
                    b.Navigation("TopicsPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
